[build]
  base = "GoTravel"
  command = "npm run build"
  publish = "GoTravel/dist"

[functions]
  directory = "functions"

[build.environment]
  NODE_VERSION = "14.x"  # O la versión que estés utilizando

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
